table1 = {
	{"nevertheless","тем не менш"},
	{"disease","захворювання"},
	{"discussion","дискусія"},
	{"development ","розробка"},
	{"friend","друг"},
	{"insurance","гарантія"},
	{"journey","подорож"},
	{"learning","навчання"},
	{"depend","залежати"},
	{"fool","дурень"},
	{"simple","простий"},
	{"afternoon","вдень"},
	{"computer","комп'ютер"},
	{"devote","присвячувати"},
	{"embarrass","збентежити"},
	{"jewellery","прикраса"},
	{"needle","голка"},
	{"opinion","думка"},
	{"observe","спостерігати"},
	{"persuade","переконувати"},
	{"rumor","чутка"},
}